meta_product_name: "Lost Ark Honing Symulator"
meta_title: "Lost Ark Honing Symulator - Don't speculate, Simulate"
meta_description: "Simulate in-game honing process without wasting your resources"
meta_image: "navbar2.jpg" # should exist in `app/assets/images/`
twitter_account: "@radzikwow"   # required for Twitter Cards
